# Generated by Django 5.0.7 on 2026-05-19 06:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name_en', models.CharField(db_index=True, max_length=255)),
                ('name_ar', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('description_en', models.TextField()),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('physical', 'Physical'), ('digital', 'Digital')], default='physical', max_length=16)),
                ('sku', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('out_of_stock', 'Out of Stock'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('price_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_gbp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sale_price_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sale_price_gbp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sale_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock', models.PositiveIntegerField(db_index=True, default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('sizes', models.JSONField(blank=True, default=list)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('redeem_points', models.PositiveIntegerField(blank=True, db_index=True, help_text='Points required to redeem/purchase this product. Leave blank if not redeemable.', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_category_products', to='categories.category')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('image', models.FileField(upload_to='products/images/')),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('color', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ('-is_primary', 'created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'is_featured'], name='products_pr_status_28f1d7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'sub_category'], name='products_pr_categor_3ecf46_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku', 'is_active'], name='products_pr_sku_80897b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['warehouse', 'status'], name='products_pr_warehou_4d7de7_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('warehouse', 'name_en'), name='unique_product_name_per_warehouse'),
        ),
    ]
