# Generated by Django 5.0.7 on 2026-05-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='redeem_points',
        ),
        migrations.AddField(
            model_name='product',
            name='required_points',
            field=models.PositiveIntegerField(default=0, help_text='Points required along with cash to purchase this product (Cash + Points purchase).'),
        ),
    ]
