# Generated by Django 5.0.7 on 2026-05-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20260519_2153'),
        ('products', '0003_lowstocknotification'),
    ]

    operations = [
    ]
