# Generated by Django 3.2.25 on 2026-05-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Additional notes or cancellation reasons'),
        ),
    ]
