# Generated by Django 5.0.7 on 2026-05-21 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_cards', '0004_alter_giftcard_options_and_more'),
        ('orders', '0003_remove_order_tax_amount_order_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='applied_gift_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='gift_cards.giftcard'),
        ),
        migrations.AddField(
            model_name='order',
            name='applied_gift_wrap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='gift_cards.giftcardwrap'),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_card_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_wrap_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
