# Generated by Django 5.0.7 on 2026-05-19 06:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], db_index=True, max_length=8)),
                ('points', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('balance_after', models.PositiveIntegerField(help_text='Wallet balance immediately after this transaction')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PointWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('balance', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RedeemSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('points_per_currency_unit', models.DecimalField(decimal_places=4, default=1.0, help_text='How many points equal 1 unit of currency (e.g. 10 pts = ₹1 → set 10)', max_digits=8)),
                ('min_points_to_redeem', models.PositiveIntegerField(default=100, help_text='Minimum points a customer must have to redeem')),
                ('max_redeem_percent', models.PositiveIntegerField(default=20, help_text='Maximum % of order total that can be paid via points (0 = no cap)')),
            ],
            options={
                'verbose_name': 'Redeem Settings',
                'verbose_name_plural': 'Redeem Settings',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BillUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('bill_image', models.FileField(upload_to='redeem/bills/')),
                ('bill_number', models.CharField(blank=True, default='', max_length=100)),
                ('bill_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount on the bill (optional, for reference)', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Customer notes about the bill')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Admin remarks when approving or rejecting')),
                ('points_awarded', models.PositiveIntegerField(default=0, help_text='Points manually entered by admin upon approval')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_uploads', to='customers.customerprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
