# Generated by Django 5.0.7 on 2026-05-19 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        ('orders', '0001_initial'),
        ('redeem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billupload',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who reviewed this bill', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='bill_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='redeem.billupload'),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='pointwallet',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point_wallet', to='customers.customerprofile'),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='redeem.pointwallet'),
        ),
        migrations.AddIndex(
            model_name='billupload',
            index=models.Index(fields=['customer', 'status'], name='redeem_bill_custome_747937_idx'),
        ),
        migrations.AddIndex(
            model_name='billupload',
            index=models.Index(fields=['status', 'created_at'], name='redeem_bill_status_e0c4c1_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['wallet', 'transaction_type'], name='redeem_poin_wallet__969b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['wallet', 'created_at'], name='redeem_poin_wallet__83eb31_idx'),
        ),
    ]
