# Generated by Django 5.0.7 on 2026-05-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redeem', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billupload',
            name='bill_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Auto-generated 6-character hex code for this bill', max_length=6),
        ),
    ]
