# Generated by Django 5.0.7 on 2026-05-19 06:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name_en', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=16)),
                ('image', models.FileField(blank=True, null=True, upload_to='categories/images/')),
                ('is_major', models.BooleanField(db_index=True, default=False)),
                ('sub_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_heading_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='categories.category')),
                ('warehouse', models.ForeignKey(blank=True, help_text='If set, this category belongs to a specific warehouse. If null, it is global.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'parent'], name='categories__status_24780c_idx')],
            },
        ),
    ]
