# Generated by Django 5.0.7 on 2026-05-19 06:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('coupon_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('coupon_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], db_index=True, max_length=16)),
                ('coupon_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valid_from', models.DateTimeField(db_index=True)),
                ('valid_until', models.DateTimeField(db_index=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('region', models.CharField(choices=[('INDIA', 'India'), ('UAE', 'UAE'), ('UK', 'UK'), ('USA', 'USA')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=16)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['coupon_code', 'status'], name='coupons_cou_coupon__c9f3ce_idx'), models.Index(fields=['region', 'valid_until'], name='coupons_cou_region_83a1b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('heading_en', models.CharField(max_length=255)),
                ('heading_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_heading_en', models.CharField(blank=True, default='', max_length=255)),
                ('sub_heading_ar', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='offers/images/')),
                ('cta_button_en', models.CharField(max_length=100)),
                ('cta_button_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=16)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['warehouse', 'status'], name='coupons_off_warehou_bb6a37_idx')],
            },
        ),
    ]
