# Generated by Django 5.0.7 on 2026-05-22 05:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('customers', '0002_initial'),
        ('orders', '0004_order_applied_gift_card_order_applied_gift_wrap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='coupons.coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage_records', to='customers.customerprofile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage_records', to='orders.order')),
            ],
            options={
                'ordering': ('-used_at',),
                'indexes': [models.Index(fields=['coupon', 'customer'], name='coupons_cou_coupon__46300b_idx'), models.Index(fields=['customer', 'used_at'], name='coupons_cou_custome_6ddbb5_idx')],
                'unique_together': {('coupon', 'customer')},
            },
        ),
    ]
