from django.urls import include, path

urlpatterns = [
    path("auth/", include("apps.user_account.api_v1.api_router")),
    path("warehouses/", include("apps.warehouses.api_v1.api_router")),
    path("warehouses/<uuid:warehouse_id>/products/", include("apps.products.api_v1.warehouse_router")),
    path("warehouses/<uuid:warehouse_id>/categories/", include("apps.categories.api_v1.warehouse_router")),
    path("warehouses/<uuid:warehouse_id>/banners/", include("apps.banners.api_v1.warehouse_router")),
    path("warehouses/<uuid:warehouse_id>/offers/", include("apps.coupons.api_v1.warehouse_router")),
    path("warehouses/<uuid:warehouse_id>/coupons/", include("apps.coupons.api_v1.coupon_warehouse_router")),
    path("warehouses/<uuid:warehouse_id>/analytics/", include("apps.analytics.api_v1.warehouse_router")),
    path("warehouses/<uuid:warehouse_id>/orders/", include("apps.orders.api_v1.warehouse_router")),
    path("warehouses/<uuid:warehouse_id>/customers/", include("apps.customers.api_v1.warehouse_router")),
    path("warehouses/<uuid:warehouse_id>/settings/", include("apps.settings.api_v1.warehouse_router")),
    path("warehouses/<uuid:warehouse_id>/gift-cards/", include("apps.gift_cards.api_v1.warehouse_router")),
    path("warehouses/<uuid:warehouse_id>/couriers/", include("apps.couriers.api_v1.warehouse_router")),
    path("categories/", include("apps.categories.api_v1.api_router")),
    path("products/", include("apps.products.api_v1.api_router")),
    path("customers/", include("apps.customers.api_v1.api_router")),
    path("cart/", include("apps.cart.api_v1.api_router")),
    path("orders/", include("apps.orders.api_v1.api_router")),
    path("payments/", include("apps.payments.api_v1.api_router")),
    path("coupons/", include("apps.coupons.api_v1.api_router")),
    path("offers/", include("apps.coupons.api_v1.offers_router")),
    path("banners/", include("apps.banners.api_v1.api_router")),
    path("analytics/", include("apps.analytics.api_v1.api_router")),
    path("settings/", include("apps.settings.api_v1.api_router")),
    path("notifications/", include("apps.notifications.api_v1.api_router")),
    path("redeem/", include("apps.redeem.api_v1.api_router")),
    path("enquiries/", include("apps.user_account.api_v1.enquiries_router")),
]
