# Generated by Django 5.0.7 on 2026-05-19 06:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('exchange_rate_inr', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('exchange_rate_gbp', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('exchange_rate_usd', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Currency settings',
            },
        ),
        migrations.CreateModel(
            name='ShippingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('domestic', models.BooleanField(default=True)),
                ('international', models.BooleanField(default=True)),
                ('uk_domestic', models.BooleanField(default=True)),
                ('shipping_price_inr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_price_gbp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('express_shipping', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Shipping settings',
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('store_name_en', models.CharField(max_length=255)),
                ('store_name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('store_email', models.EmailField(max_length=254)),
                ('store_phone', models.CharField(max_length=50)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('warehouse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_settings', to='warehouses.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Store settings',
            },
        ),
    ]
