# Generated by Django 5.0.7 on 2026-05-19 06:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCardCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('cards', models.PositiveIntegerField(default=0, help_text='Number of cards in this category')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_card_categories', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('card_name', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, null=True, upload_to='gift_cards/images/')),
                ('units', models.PositiveIntegerField(default=0)),
                ('reminder_threshold', models.PositiveIntegerField(default=0)),
                ('price_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_gbp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=16)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_cards', to='warehouses.warehouse')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gift_cards', to='gift_cards.giftcardcategory')),
            ],
            options={
                'ordering': ('card_name',),
            },
        ),
        migrations.CreateModel(
            name='GiftCardWrap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('wrap_name', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, null=True, upload_to='gift_cards/wraps/')),
                ('units', models.PositiveIntegerField(default=0)),
                ('reminder_threshold', models.PositiveIntegerField(default=0)),
                ('price_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_gbp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=16)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_card_wraps', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ('wrap_name',),
            },
        ),
        migrations.AddConstraint(
            model_name='giftcardcategory',
            constraint=models.UniqueConstraint(fields=('warehouse', 'name'), name='unique_gift_card_category_per_warehouse'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['warehouse', 'status'], name='gift_cards__warehou_2e6988_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['category', 'status'], name='gift_cards__categor_9a49c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='giftcard',
            constraint=models.UniqueConstraint(fields=('warehouse', 'card_name'), name='unique_gift_card_per_warehouse'),
        ),
        migrations.AddIndex(
            model_name='giftcardwrap',
            index=models.Index(fields=['warehouse', 'status'], name='gift_cards__warehou_42b1f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='giftcardwrap',
            constraint=models.UniqueConstraint(fields=('warehouse', 'wrap_name'), name='unique_gift_card_wrap_per_warehouse'),
        ),
    ]
