# Generated by Django 5.0.7 on 2026-05-20 08:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowStockGiftCardNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('remaining_units', models.PositiveIntegerField()),
                ('threshold', models.PositiveIntegerField()),
                ('message', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('gift_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_stock_notifications', to='gift_cards.giftcard')),
            ],
            options={
                'ordering': ('-notified_at',),
                'indexes': [models.Index(fields=['is_read', 'notified_at'], name='gift_cards__is_read_42e820_idx')],
            },
        ),
        migrations.CreateModel(
            name='LowStockGiftCardWrapNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('remaining_units', models.PositiveIntegerField()),
                ('threshold', models.PositiveIntegerField()),
                ('message', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('gift_card_wrap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_stock_notifications', to='gift_cards.giftcardwrap')),
            ],
            options={
                'ordering': ('-notified_at',),
                'indexes': [models.Index(fields=['is_read', 'notified_at'], name='gift_cards__is_read_36fbf0_idx')],
            },
        ),
    ]
