# Generated by Django 5.0.7 on 2026-05-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gift_cards', '0002_auto_20260519_2247'),
        ('gift_cards', '0002_lowstockgiftcardnotification_and_more'),
    ]

    operations = [
    ]
