# Generated by Django 5.0.7 on 2026-05-21 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gift_cards', '0003_merge_20260520_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giftcard',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='giftcardcategory',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='giftcardwrap',
            options={'ordering': ('-created_at',)},
        ),
    ]
