# Generated by Django 5.0.7 on 2026-05-19 06:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name_en', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('review_en', models.TextField()),
                ('review_ar', models.TextField(blank=True, null=True)),
                ('content_en', models.TextField(blank=True)),
                ('content_ar', models.TextField(blank=True, null=True)),
                ('city_en', models.CharField(max_length=100)),
                ('city_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=16)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('headline_en', models.CharField(max_length=255)),
                ('headline_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_text_en', models.TextField(blank=True)),
                ('sub_text_ar', models.TextField(blank=True, null=True)),
                ('sub_paragraph_en', models.TextField(blank=True)),
                ('sub_paragraph_ar', models.TextField(blank=True, null=True)),
                ('cta_label_en', models.CharField(max_length=100)),
                ('cta_label_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='banners/images/')),
                ('link', models.CharField(blank=True, default='', max_length=500)),
                ('device', models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop'), ('both', 'Both')], db_index=True, default='both', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=16)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['device', 'status'], name='banners_ban_device_b5385a_idx')],
            },
        ),
    ]
