# Generated by Django 5.0.7 on 2026-05-19 06:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('warehouse_name', models.CharField(max_length=255, unique=True)),
                ('warehouse_address', models.TextField()),
                ('warehouse_location', models.CharField(choices=[('INDIA', 'India'), ('UAE', 'UAE'), ('UK', 'UK'), ('USA', 'USA')], db_index=True, max_length=16)),
                ('warehouse_details', models.JSONField(blank=True, default=dict)),
                ('delivery_to', models.JSONField(blank=True, default=list)),
                ('flag_image', models.FileField(blank=True, null=True, upload_to='warehouses/flags/')),
            ],
            options={
                'ordering': ('warehouse_name',),
                'indexes': [models.Index(fields=['warehouse_location', 'is_active'], name='warehouses__warehou_98a4cd_idx')],
            },
        ),
    ]
